// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

function resolveDatabaseUrl(raw: string): string {
    if (!raw.startsWith('file:')) {
        return raw;
    }
    const filePath = raw.replace(/^file:/, '');
    if (path.isAbsolute(filePath)) {
        return raw;
    }
    const absolute = path.resolve(process.cwd(), filePath);
    return `file:${absolute}`;
}

const file = fileURLToPath(import.meta.url);
const dir = path.dirname(file);

const databaseUrl = resolveDatabaseUrl(process.env.DATABASE_URL ?? 'file:./dev.db');

if (!databaseUrl) {
    throw new Error('DATABASE_URL is not defined');
}

export default defineConfig({
    schema: 'src/prisma/schema.prisma',
    migrations: {
        path: 'src/prisma/migrations',
    },
    datasource: {
        url: databaseUrl,
    },
});
